# Generated by Django 3.1.1 on 2020-09-09 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200908_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insur_acc_nb',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.insuranceaccount'),
        ),
    ]
