# Generated by Django 3.1.1 on 2020-09-09 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200909_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceaccount',
            name='insuranceAgency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.insuranceagency'),
        ),
    ]
