# Generated by Django 3.1.1 on 2020-09-09 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_patient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceaccount',
            name='insuranceAgency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.insuranceagency'),
        ),
    ]
