# Generated by Django 3.1.1 on 2020-09-10 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.doctor'),
        ),
    ]
