# Generated by Django 3.1.1 on 2020-09-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_document_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='observation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
