# Generated by Django 3.1.1 on 2020-09-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20200918_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='state',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Canceled', 'Canceled')], default='Canceled', max_length=20),
        ),
    ]
