# Generated by Django 3.1.1 on 2020-09-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20200919_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='state',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Canceled', 'Canceled')], default='Canceled', max_length=20, null=True),
        ),
    ]
