# Generated by Django 3.1.1 on 2020-09-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20200920_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consulted',
            field=models.BooleanField(default=False),
        ),
    ]
