# Generated by Django 3.1.1 on 2020-09-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_appointment_consulted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='state',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='Canceled', max_length=20, null=True),
        ),
    ]
