# Generated by Django 3.1.1 on 2020-09-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20200922_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
